import React, { useState } from "react";
import "./User_Product.css";

const User_Product = () => {
  const [products, setProducts] = useState([
    {
      id: 1,
      firstName: "Terry",
      lastName: "Medhurst",
      maidenName: "Smitham",
      age: 50,
      gender: "male",
      email: "atuny0@sohu.com",
      phone: "+63 791 675 8914",
      username: "atuny0",
      password: "9uQFF1Lh",
      birthDate: "2000-12-25",
      bloodGroup: "A−",
      height: 189,
      weight: 75.4,
      eyeColor: "Green",
    },
    {
      id: 2,
      firstName: "Sheldon",
      lastName: "Quigley",
      maidenName: "Cole",
      age: 28,
      gender: "male",
      email: "hbingley1@plala.or.jp",
      phone: "+7 813 117 7139",
      username: "hbingley1",
      password: "CQutx25i8r",
      birthDate: "2003-08-02",
      bloodGroup: "O+",
      height: 187,
      weight: 74,
      eyeColor: "Brown",
    },
    {
      id: 3,
      firstName: "Terrill",
      lastName: "Hills",
      maidenName: "Hoeger",
      age: 38,
      gender: "male",
      email: "rshawe2@51.la",
      phone: "+63 739 292 7942",
      username: "rshawe2",
      password: "OWsTbMUgFc",
      birthDate: "1992-12-30",
      bloodGroup: "A−",
      height: 200,
      weight: 105.3,
      eyeColor: "Gray",
    },
    {
      id: 4,
      firstName: "Miles",
      lastName: "Cummerata",
      maidenName: "Maggio",
      age: 49,
      gender: "male",
      email: "yraigatt3@nature.com",
      phone: "+86 461 145 4186",
      username: "yraigatt3",
      password: "sRQxjPfdS",
      birthDate: "1969-01-16",
      bloodGroup: "B+",
      height: 157,
      weight: 95.9,
      eyeColor: "Gray",
    },
    {
      id: 5,
      firstName: "Mavis",
      lastName: "Schultz",
      maidenName: "Yundt",
      age: 38,
      gender: "male",
      email: "kmeus4@upenn.edu",
      phone: "+372 285 771 1911",
      username: "kmeus4",
      password: "aUTdmmmbH",
      birthDate: "1968-11-03",
      bloodGroup: "A-",
      height: 188,
      weight: 106.3,
      eyeColor: "Brown",
    },
    {
      id: 6,
      firstName: "Alison",
      lastName: "Reichert",
      maidenName: "Franecki",
      age: 21,
      gender: "female",
      email: "jtreleven5@nhs.uk",
      phone: "+351 527 735 3642",
      username: "jtreleven5",
      password: "zY1nE46Zm",
      birthDate: "1969-07-21",
      bloodGroup: "A+",
      height: 149,
      weight: 105.7,
      eyeColor: "Amber",
    },
    {
      id: 7,
      firstName: "Oleta",
      lastName: "Abbott",
      maidenName: "Wyman",
      age: 31,
      gender: "female",
      email: "dpettegre6@columbia.edu",
      phone: "+62 640 802 7111",
      username: "dpettegre6",
      password: "YVmhktgYVS",
      birthDate: "1982-02-21",
      bloodGroup: "B−",
      height: 172,
      weight: 78.1,
      eyeColor: "Blue",
    },
    {
      id: 8,
      firstName: "Ewell",
      lastName: "Mueller",
      maidenName: "Durgan",
      age: 29,
      gender: "male",
      email: "ggude7@chron.com",
      phone: "+86 946 297 2275",
      username: "ggude7",
      password: "MWwlaeWcOoF6",
      birthDate: "1964-08-24",
      bloodGroup: "A−",
      height: 146,
      weight: 52.1,
      eyeColor: "Blue",
    },
    {
      id: 9,
      firstName: "Demetrius",
      lastName: "Corkery",
      maidenName: "Gleason",
      age: 22,
      gender: "male",
      email: "nloiterton8@aol.com",
      phone: "+86 356 590 9727",
      username: "nloiterton8",
      password: "HTQxxXV9Bq4",
      birthDate: "1971-03-11",
      bloodGroup: "A+",
      height: 170,
      weight: 97.1,
      eyeColor: "Green",
    },
    {
      id: 10,
      firstName: "Eleanora",
      lastName: "Price",
      maidenName: "Cummings",
      age: 37,
      gender: "female",
      email: "umcgourty9@jalbum.net",
      phone: "+60 184 408 0824",
      username: "umcgourty9",
      password: "i0xzpX",
      birthDate: "1958-08-11",
      bloodGroup: "O+",
      height: 198,
      weight: 48,
      eyeColor: "Blue",
    },
    {
      id: 11,
      firstName: "Marcel",
      lastName: "Jones",
      maidenName: "Smith",
      age: 39,
      gender: "male",
      email: "acharlota@liveinternet.ru",
      phone: "+967 253 210 0344",
      username: "acharlota",
      password: "M9lbMdydMN",
      birthDate: "1961-09-12",
      bloodGroup: "B−",
      height: 203,
      weight: 63.7,
      eyeColor: "Amber",
    },
    {
      id: 12,
      firstName: "Assunta",
      lastName: "Rath",
      maidenName: "Heller",
      age: 42,
      gender: "female",
      email: "rhallawellb@dropbox.com",
      phone: "+380 962 542 6549",
      username: "rhallawellb",
      password: "esTkitT1r",
      birthDate: "1990-12-14",
      bloodGroup: "O−",
      height: 168,
      weight: 96.8,
      eyeColor: "Gray",
    },
    {
      id: 13,
      firstName: "Trace",
      lastName: "Douglas",
      maidenName: "Lemke",
      age: 26,
      gender: "male",
      email: "lgribbinc@posterous.com",
      phone: "+1 609 937 3468",
      username: "lgribbinc",
      password: "ftGj8LZTtv9g",
      birthDate: "1967-07-23",
      bloodGroup: "O+",
      height: 181,
      weight: 56.5,
      eyeColor: "Amber",
    },
    {
      id: 14,
      firstName: "Enoch",
      lastName: "Lynch",
      maidenName: "Heidenreich",
      age: 21,
      gender: "male",
      email: "mturleyd@tumblr.com",
      phone: "+94 912 100 5118",
      username: "mturleyd",
      password: "GyLnCB8gNIp",
      birthDate: "1979-08-25",
      bloodGroup: "O+",
      height: 150,
      weight: 100.3,
      eyeColor: "Green",
    },
    {
      id: 15,
      firstName: "Jeanne",
      lastName: "Halvorson",
      maidenName: "Cummerata",
      age: 26,
      gender: "female",
      email: "kminchelle@qq.com",
      phone: "+86 581 108 7855",
      username: "kminchelle",
      password: "0lelplR",
      birthDate: "1996-02-02",
      bloodGroup: "A+",
      height: 176,
      weight: 45.7,
      eyeColor: "Amber",
    },
    {
      id: 16,
      firstName: "Trycia",
      lastName: "Fadel",
      maidenName: "Rosenbaum",
      age: 41,
      gender: "female",
      email: "dpierrof@vimeo.com",
      phone: "+420 833 708 0340",
      username: "dpierrof",
      password: "Vru55Y4tufI4",
      birthDate: "1963-07-03",
      bloodGroup: "B+",
      height: 166,
      weight: 87.2,
      eyeColor: "Gray",
    },
    {
      id: 17,
      firstName: "Bradford",
      lastName: "Prohaska",
      maidenName: "Bins",
      age: 43,
      gender: "male",
      email: "vcholdcroftg@ucoz.com",
      phone: "+420 874 628 3710",
      username: "vcholdcroftg",
      password: "mSPzYZfR",
      birthDate: "1975-10-20",
      bloodGroup: "O−",
      height: 199,
      weight: 94.3,
      eyeColor: "Brown",
    },
    {
      id: 18,
      firstName: "Arely",
      lastName: "Skiles",
      maidenName: "Monahan",
      age: 42,
      gender: "male",
      email: "sberminghamh@chron.com",
      phone: "+55 886 766 8617",
      username: "sberminghamh",
      password: "cAjfb8vg",
      birthDate: "1958-02-05",
      bloodGroup: "AB−",
      height: 192,
      weight: 97,
      eyeColor: "Amber",
    },
    {
      id: 19,
      firstName: "Gust",
      lastName: "Purdy",
      maidenName: "Abshire",
      age: 46,
      gender: "male",
      email: "bleveragei@so-net.ne.jp",
      phone: "+86 886 889 0258",
      username: "bleveragei",
      password: "UZGAiqPqWQHQ",
      birthDate: "1989-10-15",
      bloodGroup: "A−",
      height: 167,
      weight: 65.3,
      eyeColor: "Amber",
    },
    {
      id: 20,
      firstName: "Lenna",
      lastName: "Renner",
      maidenName: "Schumm",
      age: 41,
      gender: "female",
      email: "aeatockj@psu.edu",
      phone: "+1 904 601 7177",
      username: "aeatockj",
      password: "szWAG6hc",
      birthDate: "1980-01-19",
      bloodGroup: "O−",
      height: 175,
      weight: 68,
      eyeColor: "Green",
    },
  ]);

  return (
    <>
      <table className="table tbl">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">First-Name</th>
            <th scope="col">Last-Name</th>
            <th scope="col">maidenName</th>
            <th scope="col">age</th>
            <th scope="col">gender</th>
            <th scope="col">email</th>
            <th scope="col">phone</th>
            <th scope="col">username</th>
            <th scope="col">password</th>
            <th scope="col">birthDate</th>
            <th scope="col">bloodGroup</th>
            <th scope="col">height</th>
            <th scope="col">weight</th>
            <th scope="col">eyeColor</th>
          </tr>
        </thead>
        {products.map((value, index) => {
          return (
            <tbody>
              <tr>
                <th scope="row" key={index}>{value.id}</th>
                <td>{value.firstName}</td>
                <td>{value.lastName}</td>
                <td>{value.maidenName}</td>
                <td>{value.age}</td>
                <td>{value.gender}</td>
                <td>{value.email}</td>
                <td>{value.phone}</td>
                <td>{value.username}</td>
                <td>{value.password}</td>
                <td>{value.birthDate}</td>
                <td>{value.bloodGroup}</td>
                <td>{value.height}</td>
                <td>{value.weight}</td>
                <td>{value.eyeColor}</td>
              </tr>
            </tbody>
          );
        })}
      </table>
    </>
  );
};
export default User_Product;

